version: '3.8'

services:
  selenium-hub:
    image: seleniarm/hub:latest
    ports:
      - 4444:4444

  chrome:
    image: selenium/node-chrome:4.8.2
    shm_size: 2g
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    depends_on:
      - selenium-hub

  assessment:
    image: gopalcs1988/selenium-assessment
    depends_on:
      - chrome
    environment:
      - HUB_HOST=selenium-hub
      - BROWSER=chrome
    volumes:
       - ./reports:/usr/src/app/target/surefire-reports
