name: Run Assessment Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build . -t selenium-tests

    - name: Run Selenium Standalone Chrome
      run: |
        docker run -d -p 4444:4444 --name selenium-chrome selenium/standalone-chrome:latest
        sleep 10

    - name: Run Tests
      run: |
        docker run --network="host" -e HUB_HOST="localhost" selenium-tests
